### DISCUSSION TITLE
Task specific models

### DISCUSSION THREAD

**Discussion by manikyabard** [NVIDIA-NeMo/Guardrails#315] [General]
Are there any immediate plans to complete the TODO "add support to use different models for different tasks" in `llm/prompts.py`? If the solution is thought out, I can potentially help with this.

**Comment by drazvan** [comment]
Hi @manikyabard ! It would be great if you could help. The solution is not fully fleshed out. Let me follow up on this tomorrow.

**Comment by drazvan** [comment]
@manikyabard: Let's split this in two parts. 

First, we want a simple support for specifying the `task_model` as a parameter. And if it isn't specified, it should use the existing logic to use the main one. You can make a first Pull Request for this change only. 

Second, the `LLMTaskManager` should actually provide a more complete interface for "running LLM tasks", i.e., given a task name and parameters, and potentially a model name, to take care of rendering the prompt, making the LLM call, applying the output parser and ultimately returning the final result. This pattern is used in many places, e.g., https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/actions/llm/generation.py#L297-L316. 

So, adding `LLMTaskManager.run_task_async(task_name: str, model_name: str, task_args: dict)` will provide a cleaner interface. For this to work, the `LLMTaskManager` will need to have access to the initialized LLMs somehow. One solution is for the `_init_llms` (https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/rails/llm/llmrails.py#L253) function to store a dict, pass it to the `Runtime` when it is initialized, which in turn will pass it to the `LLMTaskManager` instance when initialized. 

If you want to take on the second part as well, I'm happy to provide more guidance if needed. 

Thanks!

**Comment by manikyabard** [comment]
Just to make sure I'm understanding this correctly, it looks like the model `type` would have to be the action/task name if we want the correct `llm` to be passed in during the action execution (according to `_process_start_action` in `flows/runtime.py` and `_init_llms` in `llmrails.py`).

Although determining the `task_model` should be fairly straightforward based on the `type` value, would a (`list`) parameter like `tasks` in the models config with values being a list of the task names make more sense?

Basically something like
```
models:
  - type: model_type
    engine: azure
    model: gpt-4
    parameters:
      tasks: ['generate_bot_message', 'generate_value']
      openai_api_key: "..."
      openai_api_version: "..."
      azure_endpoint: "..."
      deployment_name: "..."
```
instead of doing 
```
models:
  - type: generate_bot_message
    engine: azure
    model: gpt-4
    parameters:
      openai_api_key: "..."
      openai_api_version: "..."
      azure_endpoint: "..."
      deployment_name: "..."
  - type: generate_value
    engine: azure
    model: gpt-4
    parameters:
      openai_api_key: "..."
      openai_api_version: "..."
      azure_endpoint: "..."
      deployment_name: "..."
```
just to make the config more concise.

Also, is the second part more so to remove the `llm` parameter from the action execution calls and somehow directly make use of the llm task manager to determine these things?
