### DISCUSSION TITLE
What happens if embeddings_only is set to False?

### DISCUSSION THREAD

**Discussion by jackkwok** [NVIDIA-NeMo/Guardrails#447] [General]
The FAQ talked about `embeddings_only` boolean flag.  If it is set to `True`, user messages are matched to the canonical examples in rails.co.  But what happens if `embeddings_only` is set to `False`?  The [doc](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/configuration-guide.md#embeddings-only) doesn't seem to explain it, at least I don't see it.

The issue I have with `embeddings_only` set to True is that to many users messages are mismatched to the wrong sample utterances in rails.co.  Due to the large variety of allowed user questions, it's impracticable for me to give a comprehensive list of example utterances.

Please help me understand `embeddings_only`.

**Comment by drazvan** [comment]
Hi @jackkwok! The default value is `False`. That means that by default the LLM is used to determine the canonical form for the user message. In `0.10.0` we'll add support to specify a threshold for the confidence level. This should limit significantly the number of LLM calls, but still use the LLM for more difficult cases.

**Reply by jackkwok** [reply]
Thanks @drazvan : What does it take to add this thresholding feature?  Which files do I need to modify?  I am not sure I can wait til v0.10.0.

**Reply by drazvan** [reply]
Hi @jackkwok !

The critical bit is here:
https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/embeddings/basic.py#L273

It would need to also specify `include_distances` as per the Annoy API (https://github.com/spotify/annoy?tab=readme-ov-file#full-python-api -  see the `a.get_nns_by_vector` sginature). After the results are retrieved, you also need to filter the ones above the threshold. 

In terms of propagating a config, e.g. `search_threshold`, make sure you update this bit as well: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/rails/llm/llmrails.py#L396. 

We plan to implement this in the next couple of weeks. So, it should land in the `develop` branch by the end of this month (and released at some point mid-June). Let me know if you want to start contributing this and create a PR.

**Reply by jackkwok** [reply]
@drazvan : I see that since `0.10.0`, there is now a threshold that can be set and will be passed to Annoy.  This is great.  However, I see from the logs that LLM is always getting [called](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/actions/llm/generation.py#L438) when `embeddings_only` is set to False.  My goal is to reduce the number of LLM calls.  I want to call the LLM if and only if there are no embeddings retrieved from Annoy that are >= to the threshold.  If my understanding is correct, the current implementation is using `embeddings_only_similarity_threshold` to select what messages to inject into the LLM prompt and not as a gating criteria to call the LLM.  Please let me know if I am missing something.  Thanks.

Snippet from my `config.yaml`:
```
rails:
  dialog:
    user_messages:
      # Whether to use only the embeddings when interpreting the user's message
      embeddings_only: False
      embeddings_only_similarity_threshold: 0.725
      embeddings_only_fallback_intent: "unknown message"

```
I also tried setting the configs according to the [user guide](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user-guides/configuration-guide.md#embeddings-only). But in this case, LLM is never called.

```
rails:
  dialog:
    user_messages:
      # Whether to use only the embeddings when interpreting the user's message
      embeddings_only: True
      embeddings_only_similarity_threshold: 0.725
      # When the fallback is set to None, if the similarity is below the threshold, the user intent is computed normally using the LLM.
      # When it is set to a string value, that string value will be used as the intent.
      embeddings_only_fallback_intent: None
```

I am using `0.13.0`.
