### DISCUSSION TITLE
ERROR:nemoguardrails.server.api:Access to the specified path is not allowed.

### DISCUSSION THREAD

**Discussion by NirnayK** [NVIDIA-NeMo/Guardrails#553] [Q&A] [answered]
I am trying to use custom_embedding_search_provider but for some reason it keeps giving me error :

ERROR:nemoguardrails.server.api:Access to the specified path is not allowed.
Traceback (most recent call last):
File "/nemoguardrails/nemoguardrails/server/api.py", line 273, in chat_completion
llm_rails = _get_rails(config_ids)
File "/nemoguardrails/nemoguardrails/server/api.py", line 230, in _get_rails
raise ValueError("Access to the specified path is not allowed.")
ValueError: Access to the specified path is not allowed.

I tried it with the exact same config as to https://github.com/NVIDIA/NeMo-Guardrails/tree/develop/tests/test_configs/with_custom_embedding_search_provider but it keeps giving me the same issue.

**Comment by Pouyanpi** [comment]
Hi @NirnayK,

I assume you are using following command:

```bash
nemoguardrails server --config=path/to/config
```

Can you share with me which version of nemoguardrails you are using? I think using the absolute path to the config would resolve this issue.

**Reply by NirnayK** [reply]
I am using the latest commit of the develop branch. I guess version 9.0. 
This works : (older)
full_path = os.path.normpath(os.path.join(app.rails_config_path, config_id))
        if not full_path.startswith(app.rails_config_path):
            raise Exception("Not allowed.")
            
This doesnt: (newer/current)
        base_path = os.path.abspath(app.rails_config_path)
        full_path = os.path.normpath(os.path.join(base_path, config_id))

        if not full_path.startswith(base_path + os.sep):
            raise ValueError("Access to the specified path is not allowed.")

Lets say i give path to config = folder
Now whether i add a / or not the newer code always appends it in the end and it returns false.
Also wouldnt absolute path to config mess with kb ?

**Comment by NirnayK** [comment]
Also I shifted to 8.x and tried out the config works but it never calls the custom provider. The init function is called but the search function is never called when user sends a query

**Reply by NirnayK** [reply]
@drazvan 

This the config.py

```python
import os
from typing import List
from e2enetworks.cloud import tir
# from langchain_text_splitters import SentenceTransformersTokenTextSplitter
from qdrant_client import QdrantClient
from nemoguardrails import LLMRails
from nemoguardrails.embeddings.index import EmbeddingsIndex, IndexItem


class CustomEmbeddingSearchProvider(EmbeddingsIndex):
    def __init__(self):
        self.host = os.getenv("QDRANT_HOST")
        self.key = os.getenv("QDRANT_API_KEY")
        self.collection = os.getenv("QDRANT_COLLECTION_NAME")

        assert self.host, "QDRANT URL is not set"
        assert self.key, "QDRANT API Key is not set"
        assert self.collection, "QDRANT Collection Name is not set"

        self.qdrant_client = self.get_qdrant_client()


        tir.init()
        self.tir_client = tir.ModelAPIClient()

    @property
    def embedding_size(self):
        self.embedding_size = 4096

    @property
    def cache_config(self):
        pass

    async def _get_embeddings(self, texts: List[str]):
        pass

    async def add_item(self, item: IndexItem):
        pass

    async def add_items(self, items: List[IndexItem]):
        pass

    async def build(self):
        """Build the index, after the items are added.

        This is optional, might not be needed for all implementations."""
        pass

    def get_custom_embedding(self, text: str) -> List[float]:

        data = {"prompt": text}
        try:
            response = self.tir_client.infer(model_name="e5-mistral-7b-instruct", data=data)
            result = response.get("outputs",[]).get("data",[])
            return result
        except Exception as e:
            print(f"Error while getting custom embedding: {e}")
            return []

    # def chunk_text(text: str):
    #     text_splitter = SentenceTransformersTokenTextSplitter()
    #     chunks = text_splitter.split_text(text)
    #     return chunks

    def get_qdrant_client(self) -> QdrantClient:
        qdrant_client = QdrantClient(host=self.host, port=6333, api_key=self.key)
        collection_exists = qdrant_client.collection_exists(self.collection)
        assert collection_exists, f"Collection {self.collection} does not exist"
        return qdrant_client

    async def search(self, text: str, max_results: int) -> List[IndexItem]:
        # chunks = self.chunk_text(text)
        # embeddings = [self.get_custom_embedding(chunk) for chunk in chunks]
        embedding = self.get_custom_embedding(text)
        print("Reached search")
        print("Reached search")
        print("Reached search")
        print("Reached search")
        print("Reached search")
        print("Reached search")
        print("Reached search")

        search_result = self.qdrant_client.search(
            collection_name=self.collection,
            query_vector=embedding,
            limit=max_results,
        )

        items = [hit.payload["data"] for hit in search_result]
        result = [IndexItem(text=item["text"]) for item in items]

        print("returning stuff")
        print("returning stuff")
        print("returning stuff")
        print("returning stuff")
        print("returning stuff")
        print("returning stuff")
        print("returning stuff")
        print(result)

        return result



def init(app: LLMRails):
    print("Yes")
    print("Yes")
    print("Yes")
    print("Yes")
    print("Yes")
    print("Yes")
    print("Yes")
    print("Yes")
    print("Yes")
    print("Yes")
    app.register_embedding_search_provider("custom", CustomEmbeddingSearchProvider)
```

The YES is printed at start but whenever i query it never calls upon search so I am confused reagrding that. 
I have made the kb folder and have a dummy.md in it so that it doesnt discount the kb but no use.

**Reply by drazvan** [reply]
Can you confirm you've also updated the `config.yml` file to use the custom embedding search provider?

```yaml
knowledge_base:
  embedding_search_provider:
    name: custom
```
More details here: https://docs.nvidia.com/nemo/guardrails/user_guides/advanced/embedding-search-providers.html.

**Reply by NirnayK** [reply]
Here is my config:

```yaml
core:
    embedding_search_provider:
        name: custom

knowledge_base:
    embedding_search_provider:
        name: custom

instructions:
    - type: general
      content: |
          Below is a conversation between a user and a bot called the TIR Bot.
          The bot is designed to answer questions about an AI development platform called as TIR.
          The bot is knowledgeable about the features that TIR provides.
          The bot does not use any external sources to answer any questions. Only use the knowledge base for any responses. Very important.
          If the bot does not know the answer to a question, it truthfully says it does not know.
```
